import { FormDesignElementTyping } from '/@/types/form-design/index-typing'
import { rowTyping } from "/@/types/form-design/container-element/grid/row";
import { colTyping } from "/@/types/form-design/container-element/grid/col";
import { cardTyping } from "/@/types/form-design/container-element/card/card";
import { tabsTyping } from "/@/types/form-design/container-element/tabs/tabs";
import { tabPaneTyping } from "/@/types/form-design/container-element/tabs/tab-pane";
import { collapseTyping } from "/@/types/form-design/container-element/collapse/collapse";
import { collapsePanelTyping } from "/@/types/form-design/container-element/collapse/collapse-panel";

import { Align, Justify } from '/@/enums/form-design/row-enum';
import { ContainerSizeEnum } from "/@/enums/form-design/size-enum";
import { Position } from '/@/enums/form-design/element-enum';
import { Type, TabPosition } from "/@/enums/form-design/tabs-enum";
export const container: Array<FormDesignElementTyping> = [
  {
    elementId: "",
    type: "row",
    name: "栅格",
    iconType: "custom",
    icon: "",
    formItemFlag: false,
    category: "contianer",
    internal: false,
    options: {
      customStyles: [],
      align: Align.TOP,
      gutter: 12,
      justify: Justify.START,
      wrap: true,
    } as any,
    children: [],
  },
  {
    elementId: "",
    type: "col",
    name: "栅格",
    iconType: "custom",
    icon: "",
    formItemFlag: false,
    category: "contianer",
    internal: true,
    options: {
      customStyles: [],
      flex: null,
      offset: 0,
      order: 0,
      pull: 0,
      push: 0,
      span: 12,
      xxxl: null,
      xs: null,
      sm: null,
      md: null,
      lg: null,
      xl: null,
      xxl: null,
    } as any,
    list: [],
  },
  {
    elementId: "",
    type: "card",
    name: "卡片",
    iconType: "custom",
    icon: "",
    formItemFlag: false,
    category: "contianer",
    internal: false,
    options: {
      customStyles: [],
      label: "卡片",
      headStyle: {},
      bodyStyle: {},
      bordered: true,
      hoverable: false,
      size: ContainerSizeEnum.SMALL,
    } as any,
    list: [],
  },
  {
    elementId: "",
    type: "tabs",
    name: "标签页",
    iconType: "custom",
    icon: "",
    formItemFlag: false,
    category: "contianer",
    internal: false,
    options: {
      customStyles: [],
      type: Type.LINE,
      tabPosition: TabPosition.TOP,
      tabBarGutter: 6,
      tabBarStyle: {},
      size: ContainerSizeEnum.SMALL,
      destroyInactiveTabPane: false,
      centered: false,
    },
    children: [],
  },
  {
    elementId: "",
    type: "tab-pane",
    name: "子标签",
    iconType: "custom",
    icon: "",
    formItemFlag: false,
    category: "contianer",
    internal: true,
    options: {
      customStyles: [],
      label: "tab",
      hidden: false,
      active: false,
      disabled: false,
    },
    list: [],
  },
  {
    elementId: "",
    type: "collapse",
    name: "折叠面板",
    iconType: "custom",
    icon: "",
    formItemFlag: false,
    category: "contianer",
    internal: false,
    options: {
      customStyles: [],
      accordion: false,
      destroyInactivePanel: false,
      expandIconPosition: Position.LEFT,
      ghost: false,
    } as collapseTyping,
    children: [],
  },
  {
    elementId: "",
    type: "collapse-panel",
    name: "子折叠面板",
    iconType: "custom",
    icon: "",
    formItemFlag: false,
    category: "contianer",
    internal: true,
    options: {
      customStyles: [],
      label: "collapse",
      forceRender: false,
      showArrow: true,
    } as collapsePanelTyping,
    list: [],
  },
];
