name: CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build docker
        run: |
          docker build -t mt-form-vue:dev .

      - name: Login to Docker Registry
        run: docker login -u cn-north-4@MLLGQIDRLOWDRQDJD1NM -p 49ffb799cc65b40284438c83859e66870344307e8132ce17fe63904e0e562c0b swr.cn-north-4.myhuaweicloud.com

      - name: Push to Docker Registry
        run: |
          docker tag mt-form-vue:dev swr.cn-north-4.myhuaweicloud.com/yuanjunjie/mt-form-vue:dev
          docker push swr.cn-north-4.myhuaweicloud.com/yuanjunjie/mt-form-vue:dev

  deploy:
    needs: [build]
    name: Deploy
    runs-on: fd-dev

    steps:
      - uses: actions/checkout@v2

      - name: Update docker images
        run: |
          sudo su
          sudo docker login -u cn-north-4@MLLGQIDRLOWDRQDJD1NM -p 49ffb799cc65b40284438c83859e66870344307e8132ce17fe63904e0e562c0b swr.cn-north-4.myhuaweicloud.com
          sudo docker pull swr.cn-north-4.myhuaweicloud.com/yuanjunjie/mt-form-vue:dev

      - name: Login to Docker Registry 
        run: |
          sudo su
          sudo docker login -u cn-north-4@MLLGQIDRLOWDRQDJD1NM -p 49ffb799cc65b40284438c83859e66870344307e8132ce17fe63904e0e562c0b swr.cn-north-4.myhuaweicloud.com

      - name: Run
        run: |
          sudo su
          sudo docker compose -f docker-compose.yml up -d
          
      - name: Clear Docker Cache
        run: |
          sudo su
          sudo docker login -u cn-north-4@MLLGQIDRLOWDRQDJD1NM -p 49ffb799cc65b40284438c83859e66870344307e8132ce17fe63904e0e562c0b swr.cn-north-4.myhuaweicloud.com
          sudo docker image prune -f
          sudo docker volume prune -f
